# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install docker
        uses: docker/setup-docker@v1

      - name: Build the Docker image
        run: docker build -t test-docker-image .

      - name: Run the Docker image
        run: docker run -d -p 8080:8080 test-docker-image

      - name: Wait for the Docker image to start
        run: sleep 5

      - name: Test the Docker image
        run: curl -sSf http://localhost:8080

      - name: Test cases
        run: docker exec -it $(docker ps -q) go test -v ./...
